# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-29 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180828_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 15, 21, 16, 537534), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='modelo',
            field=models.ForeignKey(blank=True, help_text='Modelo del veh\xedculo ', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Modelo_Auto'),
        ),
    ]
