# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-08 15:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20180802_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300)),
                ('apellido', models.CharField(blank=True, max_length=300)),
                ('dni', models.CharField(blank=True, max_length=300)),
                ('domicilio', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=300)),
                ('celular', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('referenciado', models.CharField(blank=True, max_length=300)),
                ('nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_ini', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='produccion',
            name='dni_c',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='dni',
            field=models.CharField(blank=True, help_text='Otro nmero de dni', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 15, 29, 48, 605144), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
