# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-08 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180808_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='marca_p',
            new_name='marca_producto',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 17, 50, 4, 792865), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
