# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-09 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180809_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='estado',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 9, 59, 47, 468418), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
